version: '2.3'
services:

  cards:
    image: cards:latest
    container_name: cards
    restart: "no"
    depends_on:
      - postgres
      - keycloak
    environment:
      POSTGRES_HOST: postgres
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8080
      KEYCLOAK_REALM: cards_realm
      KEYCLOAK_CLIENT: client
    expose:
      - 8080
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: cards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/schema/init.sql:/docker-entrypoint-initdb.d/init.sql

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: cards
      DB_SCHEMA: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    ports:
      - "8484:8080"
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
