server:
  port: 8181

spring:
  application:
    name: cards
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/cards?currentSchema=cards
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog.yml

keycloak:
  auth-server-url: http://${KEYCLOAK_HOST:localhost}:8080/auth
#  proxy-url: http://localhost:8080/auth
  realm: cards_realm
  resource: client
  public-client: true
  bearer-only: true
  credentials:
    secret: nRvJMqMdD1yk4H5m3L5b8RB6PONZ09ZR
