server:
  port: 8080

spring:
  application:
    name: cards
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/cards?currentSchema=cards
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog.yml

keycloak:
  auth-server-url: http://localhost:8484/auth
  realm: cards_realm
  resource: client
  public-client: true
