INSERT INTO cards.card VALUES (nextval('seq_card'), 'Ургант помог', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Марк', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Колян', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Арт-директор', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Волк', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Волкан', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Джокер', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Джо', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Юнусабад', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Склад грязи', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Золотая цепь', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Горгород', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Сдавленно кекать', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Мэр', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Алиса', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Гуру', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Константин', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Мафия 2', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Свежий воздух', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Копил долго', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Любил тайно', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Купил вольво', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Полил пальму', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Башня', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Блокнот', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Путь стал замысловат', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Финиш', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Да', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Нет', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Сунь Дзы', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Лао Цсы', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Эллипсизм', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Кот', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Собянин', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Паребрик', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Парадная', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Выстрел с ноги', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Вот так вот', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Александр Невский', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Купчино', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Переплетено', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Всего лишь писатель', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Греция', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Кек', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Чебурек', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Ковид', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Дабстеп', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Самса', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Ложиться спать', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Анекдот', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Проверка', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Тестовый ответ', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Дед Максим', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Понедельник', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Кира', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Рукопись', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Телефон на верёвочке', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Чувак это репчик', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Лапух', 'OK');
INSERT INTO cards.card VALUES (nextval('seq_card'), 'Золотые часы', 'OK');

INSERT INTO cards.question VALUES (nextval('seq_question'), 'Кто убил Марка?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Что нам делать в Греции?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Правда или действие?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Сколько зарабатываешь?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Где лучшие тусовки?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'У вас продаётся славянский шкаф?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Куда несёшся?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Что делать?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Тварь ли я дрожащая или право имею?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Хау мач ис зе фиш?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'От чего так в России берёзы шумят?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'За что аборигены съели Кука?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Кто мы и откуда, откуда?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Кому нужен ломтик июльского неба?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'От чего люди не летают?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Правда или действие?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Где твои семнадцать лет?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Куда уходит детство?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Есть ли жизнь на Марсе?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Что день грядущий мне готовит?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Сколько же стоит твоя свобода?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Жизнь или кошелёк?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Почём опиум для народа?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Есть кто живой?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Стой, кто идёт?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'В чём сила, брат?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Сколько стоит шмот?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Что? Где? Когда?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Где эта улица? Где этот дом? Где лучшие тусовки?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Кому добавки?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'С чего начинается родина?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Сколько вешать в граммах?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Куда смотрит милиция?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Ху лет зе догс аут?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Вот ис лов?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Куда приводят мечты?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Что в имени тебе моём?', 'OK');
INSERT INTO cards.question VALUES (nextval('seq_question'), 'Кто если не мы?', 'OK');
