INSERT INTO cards.card VALUES (1, 'Ургант помог', 'OK');
INSERT INTO cards.card VALUES (2, 'Марк', 'OK');
INSERT INTO cards.card VALUES (3, 'Колян', 'OK');
INSERT INTO cards.card VALUES (4, 'Арт-директор', 'OK');
INSERT INTO cards.card VALUES (5, 'Волк', 'OK');
INSERT INTO cards.card VALUES (6, 'Волкан', 'OK');
INSERT INTO cards.card VALUES (7, 'Джокер', 'OK');
INSERT INTO cards.card VALUES (8, 'Джо', 'OK');
INSERT INTO cards.card VALUES (9, 'Юнусабад', 'OK');
INSERT INTO cards.card VALUES (10, 'Склад грязи', 'OK');
INSERT INTO cards.card VALUES (11, 'Золотая цепь', 'OK');
INSERT INTO cards.card VALUES (12, 'Горгород', 'OK');
INSERT INTO cards.card VALUES (13, 'Сдавленно кекать', 'OK');
INSERT INTO cards.card VALUES (14, 'Мэр', 'OK');
INSERT INTO cards.card VALUES (15, 'Алиса', 'OK');
INSERT INTO cards.card VALUES (16, 'Гуру', 'OK');
INSERT INTO cards.card VALUES (17, 'Константин', 'OK');
INSERT INTO cards.card VALUES (18, 'Мафия 2', 'OK');
INSERT INTO cards.card VALUES (19, 'Свежий воздух', 'OK');
INSERT INTO cards.card VALUES (20, 'Копил долго', 'OK');
INSERT INTO cards.card VALUES (21, 'Любил тайно', 'OK');
INSERT INTO cards.card VALUES (22, 'Купил вольво', 'OK');
INSERT INTO cards.card VALUES (23, 'Полил пальму', 'OK');
INSERT INTO cards.card VALUES (24, 'Башня', 'OK');
INSERT INTO cards.card VALUES (25, 'Блокнот', 'OK');
INSERT INTO cards.card VALUES (26, 'Путь стал замысловат', 'OK');
INSERT INTO cards.card VALUES (27, 'Финиш', 'OK');
INSERT INTO cards.card VALUES (28, 'Да', 'OK');
INSERT INTO cards.card VALUES (29, 'Нет', 'OK');
INSERT INTO cards.card VALUES (30, 'Сунь Дзы', 'OK');
INSERT INTO cards.card VALUES (31, 'Лао Цсы', 'OK');
INSERT INTO cards.card VALUES (32, 'Эллипсизм', 'OK');
INSERT INTO cards.card VALUES (33, 'Кот', 'OK');
INSERT INTO cards.card VALUES (34, 'Собянин', 'OK');
INSERT INTO cards.card VALUES (35, 'Паребрик', 'OK');
INSERT INTO cards.card VALUES (36, 'Парадная', 'OK');
INSERT INTO cards.card VALUES (37, 'Выстрел с ноги', 'OK');
INSERT INTO cards.card VALUES (38, 'Вот так вот', 'OK');
INSERT INTO cards.card VALUES (39, 'Александр Невский', 'OK');
INSERT INTO cards.card VALUES (40, 'Купчино', 'OK');
INSERT INTO cards.card VALUES (41, 'Переплетено', 'OK');
INSERT INTO cards.card VALUES (42, 'Всего лишь писатель', 'OK');
INSERT INTO cards.card VALUES (43, 'Греция', 'OK');
INSERT INTO cards.card VALUES (44, 'Кек', 'OK');
INSERT INTO cards.card VALUES (45, 'Чебурек', 'OK');
INSERT INTO cards.card VALUES (46, 'Ковид', 'OK');
INSERT INTO cards.card VALUES (47, 'Дабстеп', 'OK');
INSERT INTO cards.card VALUES (48, 'Самса', 'OK');
INSERT INTO cards.card VALUES (49, 'Ложиться спать', 'OK');
INSERT INTO cards.card VALUES (50, 'Анекдот', 'OK');
INSERT INTO cards.card VALUES (51, 'Проверка', 'OK');
INSERT INTO cards.card VALUES (52, 'Тестовый ответ', 'OK');
INSERT INTO cards.card VALUES (53, 'Дед Максим', 'OK');
INSERT INTO cards.card VALUES (54, 'Понедельник', 'OK');
INSERT INTO cards.card VALUES (55, 'Кира', 'OK');
INSERT INTO cards.card VALUES (56, 'Рукопись', 'OK');
INSERT INTO cards.card VALUES (57, 'Телефон на верёвочке', 'OK');
INSERT INTO cards.card VALUES (58, 'Чувак это репчик', 'OK');
INSERT INTO cards.card VALUES (59, 'Лапух', 'OK');
INSERT INTO cards.card VALUES (60, 'Золотые часы', 'OK');

INSERT INTO cards.question VALUES (1, 'Кто убил Марка?', 'OK');
INSERT INTO cards.question VALUES (2, 'Что нам делать в Греции?', 'OK');
INSERT INTO cards.question VALUES (3, 'Правда или действие?', 'OK');
INSERT INTO cards.question VALUES (4, 'Сколько зарабатываешь?', 'OK');
INSERT INTO cards.question VALUES (5, 'Где лучшие тусовки?', 'OK');
INSERT INTO cards.question VALUES (6, 'У вас продаётся славянский шкаф?', 'OK');
INSERT INTO cards.question VALUES (7, 'Куда несёшся?', 'OK');
INSERT INTO cards.question VALUES (8, 'Что делать?', 'OK');
INSERT INTO cards.question VALUES (9, 'Тварь ли я дрожащая или право имею?', 'OK');
INSERT INTO cards.question VALUES (10, 'Хау мач ис зе фиш?', 'OK');
INSERT INTO cards.question VALUES (11, 'От чего так в России берёзы шумят?', 'OK');
INSERT INTO cards.question VALUES (12, 'За что аборигены съели Кука?', 'OK');
INSERT INTO cards.question VALUES (13, 'Кто мы и откуда, откуда?', 'OK');
INSERT INTO cards.question VALUES (14, 'Кому нужен ломтик июльского неба?', 'OK');
INSERT INTO cards.question VALUES (15, 'От чего люди не летают?', 'OK');
INSERT INTO cards.question VALUES (16, 'Правда или действие?', 'OK');
INSERT INTO cards.question VALUES (17, 'Где твои семнадцать лет?', 'OK');
INSERT INTO cards.question VALUES (18, 'Куда уходит детство?', 'OK');
INSERT INTO cards.question VALUES (19, 'Есть ли жизнь на Марсе?', 'OK');
INSERT INTO cards.question VALUES (20, 'Что день грядущий мне готовит?', 'OK');
INSERT INTO cards.question VALUES (21, 'Сколько же стоит твоя свобода?', 'OK');
INSERT INTO cards.question VALUES (22, 'Жизнь или кошелёк?', 'OK');
INSERT INTO cards.question VALUES (23, 'Почём опиум для народа?', 'OK');
INSERT INTO cards.question VALUES (24, 'Есть кто живой?', 'OK');
INSERT INTO cards.question VALUES (25, 'Стой, кто идёт?', 'OK');
INSERT INTO cards.question VALUES (26, 'В чём сила, брат?', 'OK');
INSERT INTO cards.question VALUES (27, 'Сколько стоит шмот?', 'OK');
INSERT INTO cards.question VALUES (28, 'Что? Где? Когда?', 'OK');
INSERT INTO cards.question VALUES (29, 'Где эта улица? Где этот дом? Где лучшие тусовки?', 'OK');
INSERT INTO cards.question VALUES (30, 'Кому добавки?', 'OK');
INSERT INTO cards.question VALUES (31, 'С чего начинается родина?', 'OK');
INSERT INTO cards.question VALUES (32, 'Сколько вешать в граммах?', 'OK');
INSERT INTO cards.question VALUES (33, 'Куда смотрит милиция?', 'OK');
INSERT INTO cards.question VALUES (34, 'Ху лет зе догс аут?', 'OK');
INSERT INTO cards.question VALUES (35, 'Вот ис лов?', 'OK');
INSERT INTO cards.question VALUES (36, 'Куда приводят мечты?', 'OK');
INSERT INTO cards.question VALUES (37, 'Что в имени тебе моём?', 'OK');
INSERT INTO cards.question VALUES (38, 'Кто если не мы?', 'OK');
